name: Auto-tag
on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:
jobs:
  auto-tag:
    name: Auto-tag
    runs-on: ubuntu-latest
    steps:
      - name: Auto-tag
        uses: silverstripe/gha-auto-tag@v1
